version: '3.8'

services:
  postgres:
    container_name: db
    image: arminc/clair-db:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - clairnet

  clair:
    container_name: clair_clair
    image: arminc/clair-local-scan:latest
    networks:
      - clairnet
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060:6060"
      - "6061:6061"

  registry:
    image: registry:latest
    ports:
      - "5000:5000"

networks:
  clairnet:
    driver: bridge
